coverage:
  precision: 2
  round: down
  range: 70...100
  notify:
    after_n_builds: 4

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        threshold: 1% # allow this much decrease on project
    changes: false
  
comment:
  layout: "reach, diff, files"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "docs"
  - "*.md"
  - "*.rst"
  - "**/*.pb.go"
  - "types/*.pb.go"
  - "tests/*"
  - "tests/**/*"
  - "x/**/*.pb.go"
  - "app/sim_test.go"
  - "app/test_helpers.go"