linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - unconvert

linters-settings:
  exclude: ./pystarport/*
  govet:
    check-shadowing: true
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  revive:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  prealloc:
    # XXX: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.

    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: false
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: true # Report preallocation suggestions on for loops, false by default
