{ pkgs ? import <nixpkgs> {} }:
with pkgs;
let
  src_regexes = [
    "^x$"
    "^x/.*"
    "^app$"
    "^app/.*"
    "^cmd$"
    "^cmd/.*"
    "^proto$"
    "^proto/.*"
  ];
in
buildGoPackage rec {
  pname = "chain-main";
  version = "0.0.1";
  goPackagePath = "github.com/crypto-com/chain-main";
  src = lib.cleanSourceWith {
    name = "src";
    src = lib.sourceByRegex ./. src_regexes;
  };
  # deps.nix is generated by vgo2nix
  # (FIXME use the patched version here: https://github.com/yihuang/vgo2nix/tree/fix-go-module)
  goDeps = ./deps.nix;
}
