package types

import "cosmossdk.io/errors"

var (
	ErrTransferDelegationSrcNotFound    = errors.Register(ModuleName, 1, "transfer delegation source validator not found")
	ErrTransferDelegationDestNotFound   = errors.Register(ModuleName, 2, "transfer delegation destination validator not found")
	ErrTinyTransferDelegationAmount     = errors.Register(ModuleName, 3, "too few tokens to transfer (truncates to zero tokens)")
	ErrTransferDelegationToPositionSelf = errors.Register(ModuleName, 4, "cannot transfer delegation from the position to itself")
	ErrTierAlreadyExists                = errors.Register(ModuleName, 5, "tier already exists")
	ErrTierHasActivePositions           = errors.Register(ModuleName, 6, "tier has active positions")
	ErrTierIsCloseOnly                  = errors.Register(ModuleName, 7, "tier is close only")
	ErrInvalidAmount                    = errors.Register(ModuleName, 8, "invalid amount")
	ErrMinLockAmountNotMet              = errors.Register(ModuleName, 9, "min lock amount not met")
	ErrActiveRedelegation               = errors.Register(ModuleName, 10, "cannot transfer delegation with active incoming redelegation")
	ErrValidatorNotBonded               = errors.Register(ModuleName, 11, "validator is not bonded")
	ErrInsufficientBonusPool            = errors.Register(ModuleName, 12, "insufficient bonus pool balance")
	ErrPositionNotDelegated             = errors.Register(ModuleName, 13, "position is not delegated")
	ErrExitLockDurationNotReached       = errors.Register(ModuleName, 14, "exit lock duration not reached")
	ErrPositionTriggeredExit            = errors.Register(ModuleName, 15, "position has triggered exit")
	ErrRedelegationToSameValidator      = errors.Register(ModuleName, 16, "redelegation to same validator")
	ErrTierNotFound                     = errors.Register(ModuleName, 17, "tier not found")
	ErrPositionNotFound                 = errors.Register(ModuleName, 18, "position not found")
	ErrTierStore                        = errors.Register(ModuleName, 19, "tier store operation failed")
	ErrPositionCountStore               = errors.Register(ModuleName, 20, "tier position count store operation failed")
	ErrPositionStore                    = errors.Register(ModuleName, 21, "position store operation failed")
	ErrNotPositionOwner                 = errors.Register(ModuleName, 22, "position owner mismatch")
	ErrPositionDelegated                = errors.Register(ModuleName, 23, "position is delegated")
	ErrExitNotTriggered                 = errors.Register(ModuleName, 24, "exit has not been triggered")
	ErrPositionUnbonding                = errors.Register(ModuleName, 25, "position is unbonding")
	ErrExitLockDurationElapsed          = errors.Register(ModuleName, 26, "exit lock duration has elapsed, clear position first")
	ErrInvalidTierID                    = errors.Register(ModuleName, 27, "tier id must be non-zero")
	ErrValidatorPositionCountStore      = errors.Register(ModuleName, 28, "validator position count store operation failed")
	ErrInvalidPositionID                = errors.Register(ModuleName, 29, "invalid position id")
)
