package types

import "cosmossdk.io/errors"

var (
	ErrBadTransferDelegationSrc     = errors.Register(ModuleName, 1, "transfer delegation source validator not found")
	ErrBadTransferDelegationDest    = errors.Register(ModuleName, 2, "transfer delegation destination validator not found")
	ErrTinyTransferDelegationAmount = errors.Register(ModuleName, 3, "too few tokens to transfer (truncates to zero tokens)")
	ErrTransferDelegationToPoolSelf = errors.Register(ModuleName, 4, "cannot transfer delegation from the pool to itself")
	ErrTierAlreadyExists            = errors.Register(ModuleName, 5, "tier already exists")
	ErrTierHasActivePositions       = errors.Register(ModuleName, 6, "tier has active positions")
	ErrTierIsCloseOnly              = errors.Register(ModuleName, 7, "tier is close only")
	ErrInvalidAmount                = errors.Register(ModuleName, 8, "invalid amount")
	ErrMinLockAmountNotMet          = errors.Register(ModuleName, 9, "min lock amount not met")
	ErrActiveRedelegation           = errors.Register(ModuleName, 10, "cannot transfer delegation with active incoming redelegation")
	ErrValidatorNotBonded           = errors.Register(ModuleName, 11, "validator is not bonded")
	ErrInsufficientBonusPool        = errors.Register(ModuleName, 12, "insufficient bonus pool balance")
	ErrPositionNotDelegated         = errors.Register(ModuleName, 13, "position is not delegated")
	ErrPositionAlreadyDelegated     = errors.Register(ModuleName, 14, "position is already delegated")
	ErrExitLockDurationNotReached   = errors.Register(ModuleName, 15, "exit lock duration not reached")
	ErrPositionTriggeredExit        = errors.Register(ModuleName, 16, "position has triggered exit")
	ErrRedelegationToSameValidator  = errors.Register(ModuleName, 17, "redelegation to same validator")
	ErrTierNotFound                 = errors.Register(ModuleName, 18, "tier not found")
	ErrPositionNotFound             = errors.Register(ModuleName, 19, "position not found")
	ErrTierStore                    = errors.Register(ModuleName, 20, "tier store operation failed")
	ErrPositionCountStore           = errors.Register(ModuleName, 21, "tier position count store operation failed")
	ErrPositionStore                = errors.Register(ModuleName, 22, "position store operation failed")
	ErrNotPositionOwner             = errors.Register(ModuleName, 23, "unauthorized: signer is not position owner")
	ErrPositionDelegated            = errors.Register(ModuleName, 25, "position is delegated")
	ErrExitNotTriggered             = errors.Register(ModuleName, 26, "exit has not been triggered")
	ErrPositionUnbonding            = errors.Register(ModuleName, 27, "position is unbonding")
	ErrPositionAmountZero           = errors.Register(ModuleName, 28, "position amount is zero")
	ErrExitLockDurationElapsed      = errors.Register(ModuleName, 29, "exit lock duration has elapsed, clear position first")
)
