package types

import "cosmossdk.io/errors"

var (
	ErrBadTransferDelegationSrc     = errors.Register(ModuleName, 1, "transfer delegation source validator not found")
	ErrBadTransferDelegationDest    = errors.Register(ModuleName, 2, "transfer delegation destination validator not found")
	ErrTinyTransferDelegationAmount = errors.Register(ModuleName, 3, "too few tokens to transfer (truncates to zero tokens)")
	ErrTransferDelegationToPoolSelf = errors.Register(ModuleName, 4, "cannot transfer delegation from the pool to itself")
	ErrTierAlreadyExists            = errors.Register(ModuleName, 5, "tier already exists")
	ErrTierHasActivePositions       = errors.Register(ModuleName, 6, "tier has active positions")
	ErrTierIsCloseOnly              = errors.Register(ModuleName, 7, "tier is close only")
	ErrInvalidAmount                = errors.Register(ModuleName, 8, "invalid amount")
	ErrMinLockAmountNotMet          = errors.Register(ModuleName, 9, "min lock amount not met")
	ErrActiveRedelegation           = errors.Register(ModuleName, 10, "cannot transfer delegation with active incoming redelegation")
	ErrValidatorNotBonded           = errors.Register(ModuleName, 11, "validator is not bonded")
	ErrInsufficientBonusPool        = errors.Register(ModuleName, 12, "insufficient bonus pool balance")
	ErrPositionNotDelegated         = errors.Register(ModuleName, 13, "position is not delegated")
	ErrPositionAlreadyDelegated     = errors.Register(ModuleName, 14, "position is already delegated")
	ErrExitLockDurationNotReached   = errors.Register(ModuleName, 15, "exit lock duration not reached")
	ErrPositionExiting              = errors.Register(ModuleName, 16, "position is exiting")
	ErrRedelegationToSameValidator  = errors.Register(ModuleName, 17, "redelegation to same validator")
	ErrTierNotFound                 = errors.Register(ModuleName, 18, "tier not found")
	ErrPositionNotFound             = errors.Register(ModuleName, 19, "position not found")
	ErrInvalidValidatorAddress      = errors.Register(ModuleName, 20, "invalid validator address")
	ErrMapUnbondingToPosition       = errors.Register(ModuleName, 21, "failed to map unbonding id to tier position")
	ErrEmitTypedEvent               = errors.Register(ModuleName, 22, "failed to emit typed event")
	ErrTierStore                    = errors.Register(ModuleName, 23, "tier store operation failed")
	ErrPositionCountStore           = errors.Register(ModuleName, 24, "tier position count store operation failed")
	ErrPositionStore                = errors.Register(ModuleName, 25, "position store operation failed")
	ErrNotPositionOwner             = errors.Register(ModuleName, 26, "unauthorized: signer is not position owner")
	ErrPersistPosition              = errors.Register(ModuleName, 27, "failed to persist position")
	ErrClaimAndRefreshPosition      = errors.Register(ModuleName, 28, "claim and refresh position failed")
	ErrUpdateBaseRewardsPerShare    = errors.Register(ModuleName, 29, "failed to update base rewards per share")
	ErrDelegateToValidator          = errors.Register(ModuleName, 30, "delegate to validator failed")
	ErrLockFundsForPosition         = errors.Register(ModuleName, 31, "lock funds for tier position failed")
	ErrCreateTierPosition           = errors.Register(ModuleName, 32, "create tier position failed")
)
