// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainmain/tieredrewards/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RedelegationMapping binds a staking redelegation entry (by unbonding id) to
// a tier position id, so tier can route per-entry slash/completion hooks.
type RedelegationMapping struct {
	UnbondingId uint64 `protobuf:"varint,1,opt,name=unbonding_id,json=unbondingId,proto3" json:"unbonding_id,omitempty"`
	PositionId  uint64 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
}

func (m *RedelegationMapping) Reset()         { *m = RedelegationMapping{} }
func (m *RedelegationMapping) String() string { return proto.CompactTextString(m) }
func (*RedelegationMapping) ProtoMessage()    {}
func (*RedelegationMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{0}
}
func (m *RedelegationMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RedelegationMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RedelegationMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RedelegationMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedelegationMapping.Merge(m, src)
}
func (m *RedelegationMapping) XXX_Size() int {
	return m.Size()
}
func (m *RedelegationMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_RedelegationMapping.DiscardUnknown(m)
}

var xxx_messageInfo_RedelegationMapping proto.InternalMessageInfo

func (m *RedelegationMapping) GetUnbondingId() uint64 {
	if m != nil {
		return m.UnbondingId
	}
	return 0
}

func (m *RedelegationMapping) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

// ValidatorEventEntry wraps a validator address, sequence number and event for genesis export.
type ValidatorEventEntry struct {
	Validator string         `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Sequence  uint64         `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Event     ValidatorEvent `protobuf:"bytes,3,opt,name=event,proto3" json:"event"`
}

func (m *ValidatorEventEntry) Reset()         { *m = ValidatorEventEntry{} }
func (m *ValidatorEventEntry) String() string { return proto.CompactTextString(m) }
func (*ValidatorEventEntry) ProtoMessage()    {}
func (*ValidatorEventEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{1}
}
func (m *ValidatorEventEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorEventEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorEventEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorEventEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorEventEntry.Merge(m, src)
}
func (m *ValidatorEventEntry) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorEventEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorEventEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorEventEntry proto.InternalMessageInfo

func (m *ValidatorEventEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorEventEntry) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ValidatorEventEntry) GetEvent() ValidatorEvent {
	if m != nil {
		return m.Event
	}
	return ValidatorEvent{}
}

// ValidatorEventSeqEntry wraps a validator address with its current (last used) event sequence for genesis export.
type ValidatorEventSeqEntry struct {
	Validator  string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	CurrentSeq uint64 `protobuf:"varint,2,opt,name=current_seq,json=currentSeq,proto3" json:"current_seq,omitempty"`
}

func (m *ValidatorEventSeqEntry) Reset()         { *m = ValidatorEventSeqEntry{} }
func (m *ValidatorEventSeqEntry) String() string { return proto.CompactTextString(m) }
func (*ValidatorEventSeqEntry) ProtoMessage()    {}
func (*ValidatorEventSeqEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{2}
}
func (m *ValidatorEventSeqEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorEventSeqEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorEventSeqEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorEventSeqEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorEventSeqEntry.Merge(m, src)
}
func (m *ValidatorEventSeqEntry) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorEventSeqEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorEventSeqEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorEventSeqEntry proto.InternalMessageInfo

func (m *ValidatorEventSeqEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorEventSeqEntry) GetCurrentSeq() uint64 {
	if m != nil {
		return m.CurrentSeq
	}
	return 0
}

// GenesisState defines the tieredrewards module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// tiers is the full set of tiers.
	Tiers []Tier `protobuf:"bytes,2,rep,name=tiers,proto3" json:"tiers"`
	// positions is the full set of positions.
	Positions []Position `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions"`
	// next_position_id is the next auto-increment ID for positions.
	NextPositionId uint64 `protobuf:"varint,4,opt,name=next_position_id,json=nextPositionId,proto3" json:"next_position_id,omitempty"`
	// redelegation_mappings tracks positions currently undergoing a staking
	// redelegation, keyed by the entry's staking unbonding id.
	RedelegationMappings []RedelegationMapping `protobuf:"bytes,5,rep,name=redelegation_mappings,json=redelegationMappings,proto3" json:"redelegation_mappings"`
	// validator_events stores pending validator lifecycle events for lazy processing.
	ValidatorEvents []ValidatorEventEntry `protobuf:"bytes,6,rep,name=validator_events,json=validatorEvents,proto3" json:"validator_events"`
	// validator_event_seqs stores the current (last used) event sequence per validator.
	ValidatorEventSeqs []ValidatorEventSeqEntry `protobuf:"bytes,7,rep,name=validator_event_seqs,json=validatorEventSeqs,proto3" json:"validator_event_seqs"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTiers() []Tier {
	if m != nil {
		return m.Tiers
	}
	return nil
}

func (m *GenesisState) GetPositions() []Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *GenesisState) GetNextPositionId() uint64 {
	if m != nil {
		return m.NextPositionId
	}
	return 0
}

func (m *GenesisState) GetRedelegationMappings() []RedelegationMapping {
	if m != nil {
		return m.RedelegationMappings
	}
	return nil
}

func (m *GenesisState) GetValidatorEvents() []ValidatorEventEntry {
	if m != nil {
		return m.ValidatorEvents
	}
	return nil
}

func (m *GenesisState) GetValidatorEventSeqs() []ValidatorEventSeqEntry {
	if m != nil {
		return m.ValidatorEventSeqs
	}
	return nil
}

func init() {
	proto.RegisterType((*RedelegationMapping)(nil), "chainmain.tieredrewards.v1.RedelegationMapping")
	proto.RegisterType((*ValidatorEventEntry)(nil), "chainmain.tieredrewards.v1.ValidatorEventEntry")
	proto.RegisterType((*ValidatorEventSeqEntry)(nil), "chainmain.tieredrewards.v1.ValidatorEventSeqEntry")
	proto.RegisterType((*GenesisState)(nil), "chainmain.tieredrewards.v1.GenesisState")
}

func init() {
	proto.RegisterFile("chainmain/tieredrewards/v1/genesis.proto", fileDescriptor_a29049b0cc2bdb31)
}

var fileDescriptor_a29049b0cc2bdb31 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xdb, 0xb4, 0xd0, 0x75, 0x05, 0xd5, 0x36, 0x20, 0x13, 0x09, 0x27, 0x8d, 0x10, 0x44,
	0x48, 0xb1, 0xd5, 0x70, 0xad, 0x04, 0x44, 0x2a, 0xd0, 0x03, 0x52, 0x95, 0xa0, 0x4a, 0x70, 0x31,
	0x8e, 0x3d, 0x72, 0xb7, 0x6a, 0x76, 0x9d, 0xdd, 0x8d, 0x69, 0xf8, 0x0a, 0x3e, 0x86, 0x13, 0xe2,
	0x03, 0x7a, 0xac, 0x38, 0x71, 0x42, 0x28, 0xf9, 0x11, 0xe4, 0xf5, 0xda, 0x6d, 0x42, 0x31, 0x1c,
	0xb8, 0x44, 0xd9, 0x99, 0xf7, 0xe6, 0x8d, 0x67, 0x9e, 0x06, 0xb5, 0x83, 0x63, 0x9f, 0xd0, 0x91,
	0x4f, 0xa8, 0x2b, 0x09, 0x70, 0x08, 0x39, 0x7c, 0xf0, 0x79, 0x28, 0xdc, 0x64, 0xd7, 0x8d, 0x80,
	0x82, 0x20, 0xc2, 0x89, 0x39, 0x93, 0x0c, 0xd7, 0x0b, 0xa4, 0xb3, 0x80, 0x74, 0x92, 0xdd, 0xfa,
	0xa3, 0x92, 0x2a, 0xb1, 0xcf, 0xfd, 0x91, 0x2e, 0x52, 0x7f, 0x58, 0x02, 0x94, 0xd3, 0x18, 0x72,
	0xdc, 0xbd, 0x80, 0x89, 0x11, 0x13, 0x9e, 0x7a, 0xb9, 0xd9, 0x43, 0xa7, 0x6a, 0x11, 0x8b, 0x58,
	0x16, 0x4f, 0xff, 0x65, 0xd1, 0xd6, 0x5b, 0xb4, 0xdd, 0x87, 0x10, 0x4e, 0x21, 0xf2, 0x25, 0x61,
	0xf4, 0xb5, 0x1f, 0xc7, 0x84, 0x46, 0x78, 0x07, 0x6d, 0x4e, 0xe8, 0x90, 0xd1, 0x90, 0xd0, 0xc8,
	0x23, 0xa1, 0x65, 0x34, 0x8d, 0x76, 0xb5, 0x6f, 0x16, 0xb1, 0x83, 0x10, 0x37, 0x90, 0x19, 0x33,
	0x41, 0x52, 0x56, 0x8a, 0x58, 0x51, 0x08, 0x94, 0x87, 0x0e, 0xc2, 0xd6, 0x17, 0x03, 0x6d, 0x1f,
	0xf9, 0xa7, 0x24, 0xf4, 0x25, 0xe3, 0xfb, 0x09, 0x50, 0xb9, 0x4f, 0x25, 0x9f, 0xe2, 0xa7, 0x68,
	0x23, 0xc9, 0xc3, 0xaa, 0xf0, 0x46, 0x6f, 0xe7, 0xdb, 0xe7, 0xce, 0x7d, 0xdd, 0x6d, 0x41, 0x79,
	0x1e, 0x86, 0x1c, 0x84, 0x18, 0x48, 0x4e, 0x68, 0xd4, 0xbf, 0xe4, 0xe0, 0x3a, 0xba, 0x29, 0x60,
	0x3c, 0x01, 0x1a, 0x80, 0x96, 0x2d, 0xde, 0xf8, 0x05, 0x5a, 0x83, 0x54, 0xca, 0x5a, 0x6d, 0x1a,
	0x6d, 0xb3, 0xfb, 0xd8, 0xf9, 0xf3, 0xf4, 0x9d, 0xc5, 0xe6, 0x7a, 0xd5, 0xf3, 0x1f, 0x8d, 0x4a,
	0x3f, 0xa3, 0xb7, 0x3e, 0xa2, 0xbb, 0x8b, 0xe9, 0x01, 0x8c, 0xff, 0x53, 0xfb, 0x0d, 0x64, 0x06,
	0x13, 0xce, 0x81, 0x4a, 0x4f, 0xc0, 0x38, 0x1f, 0x9c, 0x0e, 0x0d, 0x60, 0xdc, 0xfa, 0x5a, 0x45,
	0x9b, 0x2f, 0x33, 0x0f, 0x0d, 0xa4, 0x2f, 0x01, 0x3f, 0x43, 0xeb, 0x99, 0x1b, 0x94, 0x9e, 0xd9,
	0x6d, 0x95, 0x7d, 0xd5, 0xa1, 0x42, 0xea, 0xaf, 0xd1, 0x3c, 0xbc, 0x87, 0xd6, 0x52, 0xa0, 0xb0,
	0x56, 0x9a, 0xab, 0x6d, 0xb3, 0xdb, 0x2c, 0x2b, 0xf0, 0x86, 0x00, 0xcf, 0x87, 0xa1, 0x48, 0xf8,
	0x15, 0xda, 0xc8, 0xf7, 0x2a, 0xac, 0x55, 0x55, 0xe1, 0x41, 0x69, 0x0b, 0x1a, 0xac, 0xab, 0x5c,
	0x92, 0x71, 0x1b, 0x6d, 0x51, 0x38, 0x93, 0xde, 0x55, 0xe7, 0x54, 0xd5, 0x00, 0x6e, 0xa5, 0xf1,
	0xc3, 0xc2, 0x3d, 0xf8, 0x04, 0xdd, 0xe1, 0x57, 0x8c, 0xe9, 0x8d, 0x32, 0x67, 0x0a, 0x6b, 0x4d,
	0xe9, 0xbb, 0x65, 0xfa, 0xd7, 0x38, 0x5a, 0xb7, 0x52, 0xe3, 0xbf, 0xa7, 0x04, 0x7e, 0x8f, 0xb6,
	0x8a, 0xf5, 0x78, 0x6a, 0xff, 0xc2, 0x5a, 0xff, 0xbb, 0xcc, 0x35, 0xe6, 0xd6, 0x32, 0xb7, 0x93,
	0x85, 0x94, 0xc0, 0x27, 0xa8, 0xb6, 0xa4, 0x90, 0xee, 0x5e, 0x58, 0x37, 0x94, 0x4a, 0xf7, 0xdf,
	0x55, 0x72, 0x1b, 0x6a, 0x21, 0x9c, 0x2c, 0x67, 0x45, 0xef, 0xe8, 0x7c, 0x66, 0x1b, 0x17, 0x33,
	0xdb, 0xf8, 0x39, 0xb3, 0x8d, 0x4f, 0x73, 0xbb, 0x72, 0x31, 0xb7, 0x2b, 0xdf, 0xe7, 0x76, 0xe5,
	0xdd, 0x5e, 0x44, 0xe4, 0xf1, 0x64, 0xe8, 0x04, 0x6c, 0xe4, 0x06, 0x7c, 0x1a, 0x4b, 0xd6, 0x61,
	0x3c, 0xea, 0x28, 0x71, 0x57, 0xfd, 0x76, 0xd4, 0x89, 0x39, 0x5b, 0x3a, 0x32, 0xea, 0xc2, 0x0c,
	0xd7, 0xd5, 0xc5, 0x78, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x53, 0xb0, 0x9c, 0xba, 0xfb, 0x04,
	0x00, 0x00,
}

func (m *RedelegationMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedelegationMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedelegationMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PositionId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x10
	}
	if m.UnbondingId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UnbondingId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorEventEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorEventEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorEventEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Event.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Sequence != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorEventSeqEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorEventSeqEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorEventSeqEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentSeq != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CurrentSeq))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorEventSeqs) > 0 {
		for iNdEx := len(m.ValidatorEventSeqs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorEventSeqs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ValidatorEvents) > 0 {
		for iNdEx := len(m.ValidatorEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RedelegationMappings) > 0 {
		for iNdEx := len(m.RedelegationMappings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RedelegationMappings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.NextPositionId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPositionId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Tiers) > 0 {
		for iNdEx := len(m.Tiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RedelegationMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UnbondingId != 0 {
		n += 1 + sovGenesis(uint64(m.UnbondingId))
	}
	if m.PositionId != 0 {
		n += 1 + sovGenesis(uint64(m.PositionId))
	}
	return n
}

func (m *ValidatorEventEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovGenesis(uint64(m.Sequence))
	}
	l = m.Event.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *ValidatorEventSeqEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.CurrentSeq != 0 {
		n += 1 + sovGenesis(uint64(m.CurrentSeq))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Tiers) > 0 {
		for _, e := range m.Tiers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextPositionId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPositionId))
	}
	if len(m.RedelegationMappings) > 0 {
		for _, e := range m.RedelegationMappings {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorEvents) > 0 {
		for _, e := range m.ValidatorEvents {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorEventSeqs) > 0 {
		for _, e := range m.ValidatorEventSeqs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RedelegationMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedelegationMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedelegationMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingId", wireType)
			}
			m.UnbondingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorEventEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorEventEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorEventEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Event", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Event.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorEventSeqEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorEventSeqEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorEventSeqEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentSeq", wireType)
			}
			m.CurrentSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentSeq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tiers = append(m.Tiers, Tier{})
			if err := m.Tiers[len(m.Tiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, Position{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPositionId", wireType)
			}
			m.NextPositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedelegationMappings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RedelegationMappings = append(m.RedelegationMappings, RedelegationMapping{})
			if err := m.RedelegationMappings[len(m.RedelegationMappings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorEvents = append(m.ValidatorEvents, ValidatorEventEntry{})
			if err := m.ValidatorEvents[len(m.ValidatorEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorEventSeqs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorEventSeqs = append(m.ValidatorEventSeqs, ValidatorEventSeqEntry{})
			if err := m.ValidatorEventSeqs[len(m.ValidatorEventSeqs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
