// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainmain/tieredrewards/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorRewardRatioEntry wraps a validator address with its reward ratio for genesis export.
type ValidatorRewardRatioEntry struct {
	Validator   string               `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	RewardRatio ValidatorRewardRatio `protobuf:"bytes,2,opt,name=reward_ratio,json=rewardRatio,proto3" json:"reward_ratio"`
}

func (m *ValidatorRewardRatioEntry) Reset()         { *m = ValidatorRewardRatioEntry{} }
func (m *ValidatorRewardRatioEntry) String() string { return proto.CompactTextString(m) }
func (*ValidatorRewardRatioEntry) ProtoMessage()    {}
func (*ValidatorRewardRatioEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{0}
}
func (m *ValidatorRewardRatioEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorRewardRatioEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorRewardRatioEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorRewardRatioEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorRewardRatioEntry.Merge(m, src)
}
func (m *ValidatorRewardRatioEntry) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorRewardRatioEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorRewardRatioEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorRewardRatioEntry proto.InternalMessageInfo

func (m *ValidatorRewardRatioEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorRewardRatioEntry) GetRewardRatio() ValidatorRewardRatio {
	if m != nil {
		return m.RewardRatio
	}
	return ValidatorRewardRatio{}
}

// UnbondingMapping maps a staking unbonding ID to a tier position ID for genesis export.
type UnbondingMapping struct {
	UnbondingId uint64 `protobuf:"varint,1,opt,name=unbonding_id,json=unbondingId,proto3" json:"unbonding_id,omitempty"`
	PositionId  uint64 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
}

func (m *UnbondingMapping) Reset()         { *m = UnbondingMapping{} }
func (m *UnbondingMapping) String() string { return proto.CompactTextString(m) }
func (*UnbondingMapping) ProtoMessage()    {}
func (*UnbondingMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{1}
}
func (m *UnbondingMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnbondingMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnbondingMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnbondingMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbondingMapping.Merge(m, src)
}
func (m *UnbondingMapping) XXX_Size() int {
	return m.Size()
}
func (m *UnbondingMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbondingMapping.DiscardUnknown(m)
}

var xxx_messageInfo_UnbondingMapping proto.InternalMessageInfo

func (m *UnbondingMapping) GetUnbondingId() uint64 {
	if m != nil {
		return m.UnbondingId
	}
	return 0
}

func (m *UnbondingMapping) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

// ValidatorEventEntry wraps a validator address, sequence number and event for genesis export.
type ValidatorEventEntry struct {
	Validator string         `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Sequence  uint64         `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Event     ValidatorEvent `protobuf:"bytes,3,opt,name=event,proto3" json:"event"`
}

func (m *ValidatorEventEntry) Reset()         { *m = ValidatorEventEntry{} }
func (m *ValidatorEventEntry) String() string { return proto.CompactTextString(m) }
func (*ValidatorEventEntry) ProtoMessage()    {}
func (*ValidatorEventEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{2}
}
func (m *ValidatorEventEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorEventEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorEventEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorEventEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorEventEntry.Merge(m, src)
}
func (m *ValidatorEventEntry) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorEventEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorEventEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorEventEntry proto.InternalMessageInfo

func (m *ValidatorEventEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorEventEntry) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ValidatorEventEntry) GetEvent() ValidatorEvent {
	if m != nil {
		return m.Event
	}
	return ValidatorEvent{}
}

// ValidatorEventNextSeqEntry wraps a validator address with its next event sequence for genesis export.
type ValidatorEventNextSeqEntry struct {
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	NextSeq   uint64 `protobuf:"varint,2,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
}

func (m *ValidatorEventNextSeqEntry) Reset()         { *m = ValidatorEventNextSeqEntry{} }
func (m *ValidatorEventNextSeqEntry) String() string { return proto.CompactTextString(m) }
func (*ValidatorEventNextSeqEntry) ProtoMessage()    {}
func (*ValidatorEventNextSeqEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{3}
}
func (m *ValidatorEventNextSeqEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorEventNextSeqEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorEventNextSeqEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorEventNextSeqEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorEventNextSeqEntry.Merge(m, src)
}
func (m *ValidatorEventNextSeqEntry) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorEventNextSeqEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorEventNextSeqEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorEventNextSeqEntry proto.InternalMessageInfo

func (m *ValidatorEventNextSeqEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorEventNextSeqEntry) GetNextSeq() uint64 {
	if m != nil {
		return m.NextSeq
	}
	return 0
}

// ValidatorPositionCountEntry wraps a validator address with its delegated position count for genesis export.
type ValidatorPositionCountEntry struct {
	Validator string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Count     uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *ValidatorPositionCountEntry) Reset()         { *m = ValidatorPositionCountEntry{} }
func (m *ValidatorPositionCountEntry) String() string { return proto.CompactTextString(m) }
func (*ValidatorPositionCountEntry) ProtoMessage()    {}
func (*ValidatorPositionCountEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{4}
}
func (m *ValidatorPositionCountEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorPositionCountEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorPositionCountEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorPositionCountEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorPositionCountEntry.Merge(m, src)
}
func (m *ValidatorPositionCountEntry) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorPositionCountEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorPositionCountEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorPositionCountEntry proto.InternalMessageInfo

func (m *ValidatorPositionCountEntry) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *ValidatorPositionCountEntry) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// GenesisState defines the tieredrewards module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// tiers is the full set of tiers.
	Tiers []Tier `protobuf:"bytes,2,rep,name=tiers,proto3" json:"tiers"`
	// positions is the full set of positions.
	Positions []Position `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions"`
	// next_position_id is the next auto-increment ID for positions.
	NextPositionId uint64 `protobuf:"varint,4,opt,name=next_position_id,json=nextPositionId,proto3" json:"next_position_id,omitempty"`
	// validator_reward_ratios is the cumulative reward ratio per validator.
	ValidatorRewardRatios []ValidatorRewardRatioEntry `protobuf:"bytes,5,rep,name=validator_reward_ratios,json=validatorRewardRatios,proto3" json:"validator_reward_ratios"`
	// unbonding_delegation_mappings maps unbonding delegation IDs to tier position IDs.
	UnbondingDelegationMappings []UnbondingMapping `protobuf:"bytes,6,rep,name=unbonding_delegation_mappings,json=unbondingDelegationMappings,proto3" json:"unbonding_delegation_mappings"`
	// redelegation_mappings maps redelegation IDs to tier position IDs.
	RedelegationMappings []UnbondingMapping `protobuf:"bytes,7,rep,name=redelegation_mappings,json=redelegationMappings,proto3" json:"redelegation_mappings"`
	// validator_events stores pending validator lifecycle events for lazy processing.
	ValidatorEvents []ValidatorEventEntry `protobuf:"bytes,8,rep,name=validator_events,json=validatorEvents,proto3" json:"validator_events"`
	// validator_event_next_seqs stores the next event sequence per validator.
	ValidatorEventNextSeqs []ValidatorEventNextSeqEntry `protobuf:"bytes,9,rep,name=validator_event_next_seqs,json=validatorEventNextSeqs,proto3" json:"validator_event_next_seqs"`
	// validator_position_counts stores the number of delegated positions per validator.
	ValidatorPositionCounts []ValidatorPositionCountEntry `protobuf:"bytes,10,rep,name=validator_position_counts,json=validatorPositionCounts,proto3" json:"validator_position_counts"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a29049b0cc2bdb31, []int{5}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTiers() []Tier {
	if m != nil {
		return m.Tiers
	}
	return nil
}

func (m *GenesisState) GetPositions() []Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *GenesisState) GetNextPositionId() uint64 {
	if m != nil {
		return m.NextPositionId
	}
	return 0
}

func (m *GenesisState) GetValidatorRewardRatios() []ValidatorRewardRatioEntry {
	if m != nil {
		return m.ValidatorRewardRatios
	}
	return nil
}

func (m *GenesisState) GetUnbondingDelegationMappings() []UnbondingMapping {
	if m != nil {
		return m.UnbondingDelegationMappings
	}
	return nil
}

func (m *GenesisState) GetRedelegationMappings() []UnbondingMapping {
	if m != nil {
		return m.RedelegationMappings
	}
	return nil
}

func (m *GenesisState) GetValidatorEvents() []ValidatorEventEntry {
	if m != nil {
		return m.ValidatorEvents
	}
	return nil
}

func (m *GenesisState) GetValidatorEventNextSeqs() []ValidatorEventNextSeqEntry {
	if m != nil {
		return m.ValidatorEventNextSeqs
	}
	return nil
}

func (m *GenesisState) GetValidatorPositionCounts() []ValidatorPositionCountEntry {
	if m != nil {
		return m.ValidatorPositionCounts
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidatorRewardRatioEntry)(nil), "chainmain.tieredrewards.v1.ValidatorRewardRatioEntry")
	proto.RegisterType((*UnbondingMapping)(nil), "chainmain.tieredrewards.v1.UnbondingMapping")
	proto.RegisterType((*ValidatorEventEntry)(nil), "chainmain.tieredrewards.v1.ValidatorEventEntry")
	proto.RegisterType((*ValidatorEventNextSeqEntry)(nil), "chainmain.tieredrewards.v1.ValidatorEventNextSeqEntry")
	proto.RegisterType((*ValidatorPositionCountEntry)(nil), "chainmain.tieredrewards.v1.ValidatorPositionCountEntry")
	proto.RegisterType((*GenesisState)(nil), "chainmain.tieredrewards.v1.GenesisState")
}

func init() {
	proto.RegisterFile("chainmain/tieredrewards/v1/genesis.proto", fileDescriptor_a29049b0cc2bdb31)
}

var fileDescriptor_a29049b0cc2bdb31 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xd1, 0x4e, 0x13, 0x41,
	0x14, 0xed, 0x02, 0x05, 0x7a, 0x4b, 0x94, 0x8c, 0xa0, 0xdb, 0x12, 0x4a, 0x69, 0x8c, 0x36, 0xc6,
	0xb6, 0x82, 0x51, 0x5f, 0x48, 0x54, 0x14, 0x95, 0x07, 0x0d, 0x29, 0x4a, 0xa2, 0x2f, 0x75, 0xe9,
	0x4e, 0x96, 0x49, 0xe8, 0xcc, 0x32, 0x33, 0x5d, 0xda, 0xbf, 0xf0, 0x4b, 0x7c, 0x32, 0x31, 0xf1,
	0x0b, 0x78, 0x24, 0x3e, 0xf9, 0x64, 0x0c, 0xfc, 0x88, 0xd9, 0xbb, 0xb3, 0xdb, 0x16, 0x6b, 0x53,
	0x0d, 0x2f, 0x4d, 0xe7, 0xce, 0xb9, 0xe7, 0xdc, 0x39, 0x3b, 0x27, 0x03, 0xe5, 0xe6, 0x81, 0xc3,
	0x78, 0xcb, 0x61, 0xbc, 0xa6, 0x19, 0x95, 0xd4, 0x95, 0xf4, 0xd8, 0x91, 0xae, 0xaa, 0x05, 0x6b,
	0x35, 0x8f, 0x72, 0xaa, 0x98, 0xaa, 0xfa, 0x52, 0x68, 0x41, 0xf2, 0x09, 0xb2, 0x3a, 0x80, 0xac,
	0x06, 0x6b, 0xf9, 0xdb, 0x23, 0x58, 0x7c, 0x47, 0x3a, 0x2d, 0x43, 0x92, 0xbf, 0x35, 0x02, 0xa8,
	0xbb, 0x3e, 0x8d, 0x71, 0xb9, 0xa6, 0x50, 0x2d, 0xa1, 0x1a, 0xb8, 0xaa, 0x45, 0x0b, 0xb3, 0xb5,
	0xe0, 0x09, 0x4f, 0x44, 0xf5, 0xf0, 0x5f, 0x54, 0x2d, 0x7d, 0xb5, 0x20, 0xb7, 0xe7, 0x1c, 0x32,
	0xd7, 0xd1, 0x42, 0xd6, 0x91, 0xb4, 0xee, 0x68, 0x26, 0xb6, 0xb8, 0x96, 0x5d, 0xf2, 0x18, 0x32,
	0x41, 0xbc, 0x69, 0x5b, 0x45, 0xab, 0x9c, 0xd9, 0x5c, 0xfd, 0xfe, 0xa5, 0xb2, 0x6c, 0x88, 0x93,
	0xc6, 0xa7, 0xae, 0x2b, 0xa9, 0x52, 0xbb, 0x5a, 0x32, 0xee, 0xd5, 0x7b, 0x3d, 0xe4, 0x3d, 0xcc,
	0x45, 0x93, 0x36, 0x64, 0xc8, 0x6a, 0x4f, 0x14, 0xad, 0x72, 0x76, 0xfd, 0x5e, 0xf5, 0xef, 0x9e,
	0x54, 0x87, 0x4d, 0xb3, 0x39, 0x75, 0xf2, 0x73, 0x25, 0x55, 0xcf, 0xca, 0x5e, 0xa9, 0xb4, 0x07,
	0xf3, 0xef, 0xf8, 0xbe, 0xe0, 0x2e, 0xe3, 0xde, 0x6b, 0xc7, 0xf7, 0x19, 0xf7, 0xc8, 0x2a, 0xcc,
	0xb5, 0xe3, 0x5a, 0x83, 0xb9, 0x38, 0xf2, 0x54, 0x3d, 0x9b, 0xd4, 0xb6, 0x5d, 0xb2, 0x02, 0x59,
	0x5f, 0x28, 0xa6, 0x99, 0xe0, 0x21, 0x62, 0x02, 0x11, 0x10, 0x97, 0xb6, 0xdd, 0xd2, 0x37, 0x0b,
	0xae, 0x25, 0x33, 0x6c, 0x05, 0x94, 0xeb, 0x4b, 0xf2, 0x22, 0x0f, 0xb3, 0x8a, 0x1e, 0xb5, 0x29,
	0x6f, 0x52, 0x23, 0x9b, 0xac, 0xc9, 0x0b, 0x48, 0xd3, 0x50, 0xca, 0x9e, 0x44, 0x83, 0xee, 0x8c,
	0x65, 0x10, 0x0e, 0x67, 0xac, 0x89, 0xda, 0x4b, 0x1d, 0xc8, 0x0f, 0x6e, 0xbf, 0xa1, 0x1d, 0xbd,
	0x4b, 0x8f, 0x2e, 0xe9, 0x08, 0x39, 0x98, 0xe5, 0xb4, 0xa3, 0x1b, 0x8a, 0x1e, 0x99, 0x23, 0xcc,
	0xf0, 0x48, 0xa0, 0xa4, 0x61, 0x29, 0xe9, 0xdf, 0x31, 0x6e, 0x3e, 0x13, 0xed, 0x4b, 0x73, 0x6f,
	0x01, 0xd2, 0xcd, 0x90, 0xce, 0xe8, 0x46, 0x8b, 0xd2, 0xe7, 0x19, 0x98, 0x7b, 0x19, 0xc5, 0x6d,
	0x57, 0x3b, 0x9a, 0x92, 0x27, 0x30, 0x1d, 0x05, 0x07, 0x45, 0xb2, 0xeb, 0xa5, 0x51, 0x4e, 0xee,
	0x20, 0xd2, 0x38, 0x68, 0xfa, 0xc8, 0x06, 0xa4, 0x43, 0xa0, 0xb2, 0x27, 0x8a, 0x93, 0xe5, 0xec,
	0x7a, 0x71, 0x14, 0xc1, 0x5b, 0x46, 0x65, 0xfc, 0x01, 0xb0, 0x89, 0xbc, 0x82, 0x4c, 0x7c, 0x97,
	0x94, 0x3d, 0x89, 0x0c, 0x37, 0x47, 0x8e, 0x60, 0xc0, 0x86, 0xa5, 0xd7, 0x4c, 0xca, 0x30, 0x8f,
	0x5e, 0xf7, 0xdf, 0xd6, 0x29, 0x3c, 0xfb, 0x95, 0xb0, 0xbe, 0x93, 0xdc, 0x58, 0xa2, 0xe0, 0x46,
	0xe2, 0x53, 0xa3, 0x3f, 0x6e, 0xca, 0x4e, 0xe3, 0x04, 0x0f, 0xfe, 0x35, 0x6f, 0xf8, 0xcd, 0xcc,
	0x48, 0x8b, 0xc1, 0x10, 0x80, 0x22, 0x01, 0x2c, 0xf7, 0xa2, 0xe6, 0xd2, 0x43, 0xea, 0x39, 0x38,
	0x65, 0x2b, 0x8a, 0xa2, 0xb2, 0xa7, 0x51, 0xfa, 0xee, 0x28, 0xe9, 0x8b, 0xf9, 0x35, 0x8a, 0x4b,
	0x09, 0xf1, 0xf3, 0x84, 0xd7, 0x20, 0x14, 0xf1, 0x60, 0x51, 0xd2, 0x61, 0x7a, 0x33, 0xff, 0xad,
	0xb7, 0xd0, 0x4f, 0x98, 0x08, 0x7d, 0x84, 0xf9, 0x9e, 0xab, 0x98, 0x2e, 0x65, 0xcf, 0xa2, 0x46,
	0x6d, 0xfc, 0x74, 0xf6, 0x1b, 0x79, 0x35, 0x18, 0xd8, 0x52, 0xe4, 0x18, 0x72, 0x17, 0x14, 0x1a,
	0x71, 0xba, 0x94, 0x9d, 0x41, 0xa9, 0x87, 0xe3, 0x4b, 0xf5, 0x27, 0xdd, 0x28, 0x5e, 0x0f, 0x86,
	0x21, 0x14, 0xe9, 0xf6, 0x0b, 0x27, 0xf7, 0x0b, 0x13, 0xa5, 0x6c, 0x40, 0xe1, 0x47, 0x63, 0x09,
	0xff, 0x19, 0x74, 0xa3, 0xdc, 0xbb, 0x90, 0x03, 0x10, 0xb5, 0xb9, 0x77, 0x72, 0x56, 0xb0, 0x4e,
	0xcf, 0x0a, 0xd6, 0xaf, 0xb3, 0x82, 0xf5, 0xe9, 0xbc, 0x90, 0x3a, 0x3d, 0x2f, 0xa4, 0x7e, 0x9c,
	0x17, 0x52, 0x1f, 0x36, 0x3c, 0xa6, 0x0f, 0xda, 0xfb, 0xd5, 0xa6, 0x68, 0xd5, 0x9a, 0xb2, 0xeb,
	0x6b, 0x51, 0x11, 0xd2, 0xab, 0xe0, 0x18, 0x35, 0xfc, 0xad, 0xe0, 0xfb, 0xd7, 0xb9, 0xf0, 0x02,
	0xe2, 0xf3, 0xb7, 0x3f, 0x8d, 0xcf, 0xd9, 0xfd, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xc9,
	0xac, 0xf2, 0x98, 0x07, 0x00, 0x00,
}

func (m *ValidatorRewardRatioEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorRewardRatioEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorRewardRatioEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RewardRatio.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UnbondingMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnbondingMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnbondingMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PositionId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x10
	}
	if m.UnbondingId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UnbondingId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorEventEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorEventEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorEventEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Event.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Sequence != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorEventNextSeqEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorEventNextSeqEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorEventNextSeqEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextSeq != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextSeq))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorPositionCountEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorPositionCountEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorPositionCountEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorPositionCounts) > 0 {
		for iNdEx := len(m.ValidatorPositionCounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorPositionCounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ValidatorEventNextSeqs) > 0 {
		for iNdEx := len(m.ValidatorEventNextSeqs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorEventNextSeqs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.ValidatorEvents) > 0 {
		for iNdEx := len(m.ValidatorEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.RedelegationMappings) > 0 {
		for iNdEx := len(m.RedelegationMappings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RedelegationMappings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.UnbondingDelegationMappings) > 0 {
		for iNdEx := len(m.UnbondingDelegationMappings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UnbondingDelegationMappings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ValidatorRewardRatios) > 0 {
		for iNdEx := len(m.ValidatorRewardRatios) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorRewardRatios[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.NextPositionId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextPositionId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Tiers) > 0 {
		for iNdEx := len(m.Tiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorRewardRatioEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.RewardRatio.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *UnbondingMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UnbondingId != 0 {
		n += 1 + sovGenesis(uint64(m.UnbondingId))
	}
	if m.PositionId != 0 {
		n += 1 + sovGenesis(uint64(m.PositionId))
	}
	return n
}

func (m *ValidatorEventEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovGenesis(uint64(m.Sequence))
	}
	l = m.Event.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *ValidatorEventNextSeqEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.NextSeq != 0 {
		n += 1 + sovGenesis(uint64(m.NextSeq))
	}
	return n
}

func (m *ValidatorPositionCountEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovGenesis(uint64(m.Count))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Tiers) > 0 {
		for _, e := range m.Tiers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextPositionId != 0 {
		n += 1 + sovGenesis(uint64(m.NextPositionId))
	}
	if len(m.ValidatorRewardRatios) > 0 {
		for _, e := range m.ValidatorRewardRatios {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.UnbondingDelegationMappings) > 0 {
		for _, e := range m.UnbondingDelegationMappings {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RedelegationMappings) > 0 {
		for _, e := range m.RedelegationMappings {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorEvents) > 0 {
		for _, e := range m.ValidatorEvents {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorEventNextSeqs) > 0 {
		for _, e := range m.ValidatorEventNextSeqs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorPositionCounts) > 0 {
		for _, e := range m.ValidatorPositionCounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorRewardRatioEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorRewardRatioEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorRewardRatioEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardRatio", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnbondingMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnbondingMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnbondingMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingId", wireType)
			}
			m.UnbondingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorEventEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorEventEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorEventEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Event", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Event.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorEventNextSeqEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorEventNextSeqEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorEventNextSeqEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextSeq", wireType)
			}
			m.NextSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextSeq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorPositionCountEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorPositionCountEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorPositionCountEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tiers = append(m.Tiers, Tier{})
			if err := m.Tiers[len(m.Tiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, Position{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPositionId", wireType)
			}
			m.NextPositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorRewardRatios", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorRewardRatios = append(m.ValidatorRewardRatios, ValidatorRewardRatioEntry{})
			if err := m.ValidatorRewardRatios[len(m.ValidatorRewardRatios)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingDelegationMappings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnbondingDelegationMappings = append(m.UnbondingDelegationMappings, UnbondingMapping{})
			if err := m.UnbondingDelegationMappings[len(m.UnbondingDelegationMappings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedelegationMappings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RedelegationMappings = append(m.RedelegationMappings, UnbondingMapping{})
			if err := m.RedelegationMappings[len(m.RedelegationMappings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorEvents = append(m.ValidatorEvents, ValidatorEventEntry{})
			if err := m.ValidatorEvents[len(m.ValidatorEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorEventNextSeqs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorEventNextSeqs = append(m.ValidatorEventNextSeqs, ValidatorEventNextSeqEntry{})
			if err := m.ValidatorEventNextSeqs[len(m.ValidatorEventNextSeqs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorPositionCounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorPositionCounts = append(m.ValidatorPositionCounts, ValidatorPositionCountEntry{})
			if err := m.ValidatorPositionCounts[len(m.ValidatorPositionCounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
