// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainmain/tieredrewards/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params holds parameters for the tieredrewards module.
type Params struct {
	// target_base_rewards_rate is the target base rewards rate for validators.
	TargetBaseRewardsRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=target_base_rewards_rate,json=targetBaseRewardsRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"target_base_rewards_rate"`
	// pool_funders is the list of addresses authorized to fund the tier rewards pool.
	// Managed via MsgUpdateParams (governance).
	PoolFunders []string `protobuf:"bytes,2,rep,name=pool_funders,json=poolFunders,proto3" json:"pool_funders,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1325376778712f90, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPoolFunders() []string {
	if m != nil {
		return m.PoolFunders
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "chainmain.tieredrewards.v1.Params")
}

func init() {
	proto.RegisterFile("chainmain/tieredrewards/v1/params.proto", fileDescriptor_1325376778712f90)
}

var fileDescriptor_1325376778712f90 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4b, 0xf3, 0x40,
	0x18, 0xc7, 0x93, 0xf7, 0x85, 0x42, 0xa3, 0x8b, 0xa5, 0x42, 0xac, 0x90, 0x16, 0x17, 0x8b, 0x90,
	0x1c, 0x45, 0x70, 0xd1, 0xc5, 0x50, 0x9c, 0x1c, 0x24, 0x82, 0x83, 0x4b, 0xb8, 0x5e, 0x1e, 0xaf,
	0x87, 0x26, 0x4f, 0xb8, 0xbb, 0x56, 0xfb, 0x2d, 0xfc, 0x18, 0x8e, 0x0e, 0xc5, 0xcf, 0xd0, 0xb1,
	0x74, 0x12, 0x87, 0x22, 0xed, 0xe0, 0xd7, 0x90, 0xde, 0x05, 0x41, 0x97, 0x87, 0x7b, 0x9e, 0xfb,
	0xf1, 0xff, 0xc3, 0xcf, 0x3b, 0x64, 0x43, 0x2a, 0x8a, 0x9c, 0x8a, 0x82, 0x68, 0x01, 0x12, 0x32,
	0x09, 0x8f, 0x54, 0x66, 0x8a, 0x8c, 0x7b, 0xa4, 0xa4, 0x92, 0xe6, 0x2a, 0x2a, 0x25, 0x6a, 0x6c,
	0xb4, 0x7e, 0xc0, 0xe8, 0x17, 0x18, 0x8d, 0x7b, 0xad, 0x1d, 0x9a, 0x8b, 0x02, 0x89, 0x99, 0x16,
	0x6f, 0xed, 0x31, 0x54, 0x39, 0xaa, 0xd4, 0x6c, 0xc4, 0x2e, 0xd5, 0x57, 0x93, 0x23, 0x47, 0x7b,
	0xdf, 0xbc, 0xec, 0xf5, 0xe0, 0xcd, 0xf5, 0x6a, 0x57, 0xa6, 0xb0, 0x81, 0x9e, 0xaf, 0xa9, 0xe4,
	0xa0, 0xd3, 0x01, 0x55, 0x90, 0x56, 0x45, 0xa9, 0xa4, 0x1a, 0x7c, 0xb7, 0xe3, 0x76, 0xeb, 0xf1,
	0xc9, 0x6c, 0xd9, 0x76, 0x3e, 0x96, 0xed, 0x7d, 0x1b, 0xac, 0xb2, 0xfb, 0x48, 0x20, 0xc9, 0xa9,
	0x1e, 0x46, 0x97, 0xc0, 0x29, 0x9b, 0xf4, 0x81, 0x2d, 0xa6, 0xa1, 0x57, 0xf5, 0xf6, 0x81, 0xbd,
	0x7c, 0xbd, 0x1e, 0xb9, 0xc9, 0xae, 0xcd, 0x8d, 0xa9, 0x82, 0xc4, 0xa6, 0x26, 0x54, 0x43, 0xe3,
	0xd4, 0xdb, 0x2e, 0x11, 0x1f, 0xd2, 0xbb, 0x51, 0x91, 0x81, 0x54, 0xfe, 0xbf, 0xce, 0xff, 0x6e,
	0x3d, 0xf6, 0x17, 0xd3, 0xb0, 0x59, 0x25, 0x9c, 0x67, 0x99, 0x04, 0xa5, 0xae, 0xb5, 0x14, 0x05,
	0x4f, 0xb6, 0x36, 0xf4, 0x85, 0x85, 0xe3, 0x9b, 0xd9, 0x2a, 0x70, 0xe7, 0xab, 0xc0, 0xfd, 0x5c,
	0x05, 0xee, 0xf3, 0x3a, 0x70, 0xe6, 0xeb, 0xc0, 0x79, 0x5f, 0x07, 0xce, 0xed, 0x19, 0x17, 0x7a,
	0x38, 0x1a, 0x44, 0x0c, 0x73, 0xc2, 0xe4, 0xa4, 0xd4, 0x18, 0xa2, 0xe4, 0xa1, 0x11, 0x49, 0xcc,
	0x0c, 0x8d, 0xf8, 0xa7, 0x3f, 0xea, 0xf5, 0xa4, 0x04, 0x35, 0xa8, 0x19, 0x2f, 0xc7, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x97, 0x11, 0xf9, 0x10, 0xa2, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolFunders) > 0 {
		for iNdEx := len(m.PoolFunders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PoolFunders[iNdEx])
			copy(dAtA[i:], m.PoolFunders[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.PoolFunders[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size := m.TargetBaseRewardsRate.Size()
		i -= size
		if _, err := m.TargetBaseRewardsRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TargetBaseRewardsRate.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.PoolFunders) > 0 {
		for _, s := range m.PoolFunders {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBaseRewardsRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetBaseRewardsRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolFunders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolFunders = append(m.PoolFunders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
