// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainmain/tieredrewards/v1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params defines the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryTierPositionRequest is the request type for the Query/TierPosition RPC method.
type QueryTierPositionRequest struct {
	PositionId uint64 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
}

func (m *QueryTierPositionRequest) Reset()         { *m = QueryTierPositionRequest{} }
func (m *QueryTierPositionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTierPositionRequest) ProtoMessage()    {}
func (*QueryTierPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{2}
}
func (m *QueryTierPositionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierPositionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierPositionRequest.Merge(m, src)
}
func (m *QueryTierPositionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierPositionRequest proto.InternalMessageInfo

func (m *QueryTierPositionRequest) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

// QueryTierPositionResponse is the response type for the Query/TierPosition RPC method.
type QueryTierPositionResponse struct {
	Position Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position"`
}

func (m *QueryTierPositionResponse) Reset()         { *m = QueryTierPositionResponse{} }
func (m *QueryTierPositionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTierPositionResponse) ProtoMessage()    {}
func (*QueryTierPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{3}
}
func (m *QueryTierPositionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierPositionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierPositionResponse.Merge(m, src)
}
func (m *QueryTierPositionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierPositionResponse proto.InternalMessageInfo

func (m *QueryTierPositionResponse) GetPosition() Position {
	if m != nil {
		return m.Position
	}
	return Position{}
}

// QueryTierPositionsByOwnerRequest is the request type for the Query/TierPositionsByOwner RPC method.
type QueryTierPositionsByOwnerRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryTierPositionsByOwnerRequest) Reset()         { *m = QueryTierPositionsByOwnerRequest{} }
func (m *QueryTierPositionsByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTierPositionsByOwnerRequest) ProtoMessage()    {}
func (*QueryTierPositionsByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{4}
}
func (m *QueryTierPositionsByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierPositionsByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierPositionsByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierPositionsByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierPositionsByOwnerRequest.Merge(m, src)
}
func (m *QueryTierPositionsByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierPositionsByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierPositionsByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierPositionsByOwnerRequest proto.InternalMessageInfo

func (m *QueryTierPositionsByOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// QueryTierPositionsByOwnerResponse is the response type for the Query/TierPositionsByOwner RPC method.
type QueryTierPositionsByOwnerResponse struct {
	Positions []Position `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions"`
}

func (m *QueryTierPositionsByOwnerResponse) Reset()         { *m = QueryTierPositionsByOwnerResponse{} }
func (m *QueryTierPositionsByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTierPositionsByOwnerResponse) ProtoMessage()    {}
func (*QueryTierPositionsByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{5}
}
func (m *QueryTierPositionsByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierPositionsByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierPositionsByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierPositionsByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierPositionsByOwnerResponse.Merge(m, src)
}
func (m *QueryTierPositionsByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierPositionsByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierPositionsByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierPositionsByOwnerResponse proto.InternalMessageInfo

func (m *QueryTierPositionsByOwnerResponse) GetPositions() []Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

// QueryAllTierPositionsRequest is the request type for the Query/AllTierPositions RPC method.
type QueryAllTierPositionsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTierPositionsRequest) Reset()         { *m = QueryAllTierPositionsRequest{} }
func (m *QueryAllTierPositionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTierPositionsRequest) ProtoMessage()    {}
func (*QueryAllTierPositionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{6}
}
func (m *QueryAllTierPositionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTierPositionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTierPositionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTierPositionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTierPositionsRequest.Merge(m, src)
}
func (m *QueryAllTierPositionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTierPositionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTierPositionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTierPositionsRequest proto.InternalMessageInfo

func (m *QueryAllTierPositionsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllTierPositionsResponse is the response type for the Query/AllTierPositions RPC method.
type QueryAllTierPositionsResponse struct {
	Positions  []Position          `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTierPositionsResponse) Reset()         { *m = QueryAllTierPositionsResponse{} }
func (m *QueryAllTierPositionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTierPositionsResponse) ProtoMessage()    {}
func (*QueryAllTierPositionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{7}
}
func (m *QueryAllTierPositionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTierPositionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTierPositionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTierPositionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTierPositionsResponse.Merge(m, src)
}
func (m *QueryAllTierPositionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTierPositionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTierPositionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTierPositionsResponse proto.InternalMessageInfo

func (m *QueryAllTierPositionsResponse) GetPositions() []Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *QueryAllTierPositionsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTiersRequest is the request type for the Query/Tiers RPC method.
type QueryTiersRequest struct {
}

func (m *QueryTiersRequest) Reset()         { *m = QueryTiersRequest{} }
func (m *QueryTiersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTiersRequest) ProtoMessage()    {}
func (*QueryTiersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{8}
}
func (m *QueryTiersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTiersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTiersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTiersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTiersRequest.Merge(m, src)
}
func (m *QueryTiersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTiersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTiersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTiersRequest proto.InternalMessageInfo

// QueryTiersResponse is the response type for the Query/Tiers RPC method.
type QueryTiersResponse struct {
	Tiers []Tier `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers"`
}

func (m *QueryTiersResponse) Reset()         { *m = QueryTiersResponse{} }
func (m *QueryTiersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTiersResponse) ProtoMessage()    {}
func (*QueryTiersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{9}
}
func (m *QueryTiersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTiersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTiersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTiersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTiersResponse.Merge(m, src)
}
func (m *QueryTiersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTiersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTiersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTiersResponse proto.InternalMessageInfo

func (m *QueryTiersResponse) GetTiers() []Tier {
	if m != nil {
		return m.Tiers
	}
	return nil
}

// QueryTierPoolBalanceRequest is the request type for the Query/TierPoolBalance RPC method.
type QueryTierPoolBalanceRequest struct {
}

func (m *QueryTierPoolBalanceRequest) Reset()         { *m = QueryTierPoolBalanceRequest{} }
func (m *QueryTierPoolBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTierPoolBalanceRequest) ProtoMessage()    {}
func (*QueryTierPoolBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{10}
}
func (m *QueryTierPoolBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierPoolBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierPoolBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierPoolBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierPoolBalanceRequest.Merge(m, src)
}
func (m *QueryTierPoolBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierPoolBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierPoolBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierPoolBalanceRequest proto.InternalMessageInfo

// QueryTierPoolBalanceResponse is the response type for the Query/TierPoolBalance RPC method.
type QueryTierPoolBalanceResponse struct {
	Balance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=balance,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"balance"`
}

func (m *QueryTierPoolBalanceResponse) Reset()         { *m = QueryTierPoolBalanceResponse{} }
func (m *QueryTierPoolBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTierPoolBalanceResponse) ProtoMessage()    {}
func (*QueryTierPoolBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{11}
}
func (m *QueryTierPoolBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierPoolBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierPoolBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierPoolBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierPoolBalanceResponse.Merge(m, src)
}
func (m *QueryTierPoolBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierPoolBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierPoolBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierPoolBalanceResponse proto.InternalMessageInfo

func (m *QueryTierPoolBalanceResponse) GetBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Balance
	}
	return nil
}

// QueryEstimateTierRewardsRequest is the request type for the Query/EstimateTierRewards RPC method.
type QueryEstimateTierRewardsRequest struct {
	PositionId uint64 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
}

func (m *QueryEstimateTierRewardsRequest) Reset()         { *m = QueryEstimateTierRewardsRequest{} }
func (m *QueryEstimateTierRewardsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEstimateTierRewardsRequest) ProtoMessage()    {}
func (*QueryEstimateTierRewardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{12}
}
func (m *QueryEstimateTierRewardsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEstimateTierRewardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEstimateTierRewardsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEstimateTierRewardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEstimateTierRewardsRequest.Merge(m, src)
}
func (m *QueryEstimateTierRewardsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEstimateTierRewardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEstimateTierRewardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEstimateTierRewardsRequest proto.InternalMessageInfo

func (m *QueryEstimateTierRewardsRequest) GetPositionId() uint64 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

// QueryEstimateTierRewardsResponse is the response type for the Query/EstimateTierRewards RPC method.
type QueryEstimateTierRewardsResponse struct {
	// base_rewards is the estimated pending base staking rewards.
	BaseRewards github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=base_rewards,json=baseRewards,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"base_rewards"`
	// bonus_rewards is the estimated pending bonus APY rewards from the tier pool.
	BonusRewards github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=bonus_rewards,json=bonusRewards,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"bonus_rewards"`
}

func (m *QueryEstimateTierRewardsResponse) Reset()         { *m = QueryEstimateTierRewardsResponse{} }
func (m *QueryEstimateTierRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEstimateTierRewardsResponse) ProtoMessage()    {}
func (*QueryEstimateTierRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{13}
}
func (m *QueryEstimateTierRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEstimateTierRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEstimateTierRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEstimateTierRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEstimateTierRewardsResponse.Merge(m, src)
}
func (m *QueryEstimateTierRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEstimateTierRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEstimateTierRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEstimateTierRewardsResponse proto.InternalMessageInfo

func (m *QueryEstimateTierRewardsResponse) GetBaseRewards() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.BaseRewards
	}
	return nil
}

func (m *QueryEstimateTierRewardsResponse) GetBonusRewards() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.BonusRewards
	}
	return nil
}

// QueryTierVotingPowerRequest is the request type for the Query/TierVotingPower RPC method.
type QueryTierVotingPowerRequest struct {
	// voter is the address to query tier voting power for.
	Voter string `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
}

func (m *QueryTierVotingPowerRequest) Reset()         { *m = QueryTierVotingPowerRequest{} }
func (m *QueryTierVotingPowerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTierVotingPowerRequest) ProtoMessage()    {}
func (*QueryTierVotingPowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{14}
}
func (m *QueryTierVotingPowerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierVotingPowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierVotingPowerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierVotingPowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierVotingPowerRequest.Merge(m, src)
}
func (m *QueryTierVotingPowerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierVotingPowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierVotingPowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierVotingPowerRequest proto.InternalMessageInfo

func (m *QueryTierVotingPowerRequest) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

// QueryTierVotingPowerResponse is the response type for the Query/TierVotingPower RPC method.
type QueryTierVotingPowerResponse struct {
	// voting_power is the sum of Amount for all delegated tier positions owned by the voter.
	VotingPower cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=voting_power,json=votingPower,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"voting_power"`
}

func (m *QueryTierVotingPowerResponse) Reset()         { *m = QueryTierVotingPowerResponse{} }
func (m *QueryTierVotingPowerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTierVotingPowerResponse) ProtoMessage()    {}
func (*QueryTierVotingPowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a1bb68642b9c95, []int{15}
}
func (m *QueryTierVotingPowerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTierVotingPowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTierVotingPowerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTierVotingPowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTierVotingPowerResponse.Merge(m, src)
}
func (m *QueryTierVotingPowerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTierVotingPowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTierVotingPowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTierVotingPowerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "chainmain.tieredrewards.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "chainmain.tieredrewards.v1.QueryParamsResponse")
	proto.RegisterType((*QueryTierPositionRequest)(nil), "chainmain.tieredrewards.v1.QueryTierPositionRequest")
	proto.RegisterType((*QueryTierPositionResponse)(nil), "chainmain.tieredrewards.v1.QueryTierPositionResponse")
	proto.RegisterType((*QueryTierPositionsByOwnerRequest)(nil), "chainmain.tieredrewards.v1.QueryTierPositionsByOwnerRequest")
	proto.RegisterType((*QueryTierPositionsByOwnerResponse)(nil), "chainmain.tieredrewards.v1.QueryTierPositionsByOwnerResponse")
	proto.RegisterType((*QueryAllTierPositionsRequest)(nil), "chainmain.tieredrewards.v1.QueryAllTierPositionsRequest")
	proto.RegisterType((*QueryAllTierPositionsResponse)(nil), "chainmain.tieredrewards.v1.QueryAllTierPositionsResponse")
	proto.RegisterType((*QueryTiersRequest)(nil), "chainmain.tieredrewards.v1.QueryTiersRequest")
	proto.RegisterType((*QueryTiersResponse)(nil), "chainmain.tieredrewards.v1.QueryTiersResponse")
	proto.RegisterType((*QueryTierPoolBalanceRequest)(nil), "chainmain.tieredrewards.v1.QueryTierPoolBalanceRequest")
	proto.RegisterType((*QueryTierPoolBalanceResponse)(nil), "chainmain.tieredrewards.v1.QueryTierPoolBalanceResponse")
	proto.RegisterType((*QueryEstimateTierRewardsRequest)(nil), "chainmain.tieredrewards.v1.QueryEstimateTierRewardsRequest")
	proto.RegisterType((*QueryEstimateTierRewardsResponse)(nil), "chainmain.tieredrewards.v1.QueryEstimateTierRewardsResponse")
	proto.RegisterType((*QueryTierVotingPowerRequest)(nil), "chainmain.tieredrewards.v1.QueryTierVotingPowerRequest")
	proto.RegisterType((*QueryTierVotingPowerResponse)(nil), "chainmain.tieredrewards.v1.QueryTierVotingPowerResponse")
}

func init() {
	proto.RegisterFile("chainmain/tieredrewards/v1/query.proto", fileDescriptor_c8a1bb68642b9c95)
}

var fileDescriptor_c8a1bb68642b9c95 = []byte{
	// 1029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x97, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0xb3, 0x01, 0x07, 0xf2, 0x1c, 0x04, 0x9d, 0xf8, 0x90, 0x6c, 0x5b, 0x3b, 0x5d, 0x4a,
	0x13, 0x22, 0xed, 0x6e, 0x13, 0x1a, 0x11, 0xda, 0x70, 0x88, 0x69, 0x41, 0x08, 0x2a, 0x82, 0xa9,
	0x8a, 0x84, 0x90, 0xac, 0xb5, 0x3d, 0x6c, 0x86, 0xda, 0x3b, 0xee, 0xce, 0xda, 0xc1, 0x8a, 0x72,
	0xe1, 0xc8, 0x01, 0x81, 0x10, 0xdf, 0x01, 0x71, 0xe2, 0x50, 0xd1, 0x1b, 0x27, 0x0e, 0x15, 0xa7,
	0xaa, 0x70, 0x40, 0x1c, 0x0a, 0x4a, 0x90, 0xf8, 0x1a, 0x68, 0x66, 0xde, 0x3a, 0x6b, 0xc7, 0x59,
	0x6f, 0x22, 0xe5, 0x92, 0x64, 0x67, 0xdf, 0x7b, 0xff, 0xdf, 0x7f, 0x76, 0xe6, 0x3d, 0x05, 0xae,
	0xd4, 0xb7, 0x3d, 0x16, 0xb4, 0x3c, 0x16, 0xb8, 0x11, 0xa3, 0x21, 0x6d, 0x84, 0x74, 0xc7, 0x0b,
	0x1b, 0xc2, 0xed, 0xae, 0xb8, 0xf7, 0x3b, 0x34, 0xec, 0x39, 0xed, 0x90, 0x47, 0x9c, 0x98, 0xfd,
	0x38, 0x67, 0x20, 0xce, 0xe9, 0xae, 0x98, 0xe7, 0xbc, 0x16, 0x0b, 0xb8, 0xab, 0x7e, 0xea, 0x70,
	0x73, 0x31, 0xa5, 0x6c, 0xdb, 0x0b, 0xbd, 0x96, 0xc0, 0xc0, 0x34, 0xfd, 0xa8, 0xd7, 0xa6, 0x71,
	0xdc, 0x72, 0x9d, 0x8b, 0x16, 0x17, 0x6e, 0xcd, 0x13, 0x54, 0x83, 0xb9, 0xdd, 0x95, 0x1a, 0x8d,
	0x3c, 0x59, 0xcf, 0x67, 0x81, 0x17, 0x31, 0x1e, 0x60, 0x6c, 0x31, 0x19, 0x1b, 0x47, 0xd5, 0x39,
	0x8b, 0xdf, 0xcf, 0xeb, 0xf7, 0x55, 0xf5, 0xe4, 0xea, 0x07, 0x7c, 0x55, 0xf0, 0xb9, 0xcf, 0xf5,
	0xba, 0xfc, 0x0b, 0x57, 0x2f, 0xf8, 0x9c, 0xfb, 0x4d, 0xea, 0x7a, 0x6d, 0xe6, 0x7a, 0x41, 0xc0,
	0x23, 0xa5, 0x86, 0x39, 0x56, 0x01, 0xc8, 0x87, 0x12, 0x68, 0x4b, 0xf9, 0xaa, 0xd0, 0xfb, 0x1d,
	0x2a, 0x22, 0xeb, 0x53, 0x98, 0x1d, 0x58, 0x15, 0x6d, 0x1e, 0x08, 0x4a, 0x6e, 0xc1, 0x94, 0xf6,
	0x3f, 0x67, 0x2c, 0x18, 0x4b, 0xf9, 0x55, 0xcb, 0x39, 0x7e, 0x63, 0x1d, 0x9d, 0x5b, 0x9e, 0x7e,
	0xf4, 0xb4, 0x34, 0xf1, 0xc3, 0x7f, 0x3f, 0x2d, 0x1b, 0x15, 0x4c, 0xb6, 0x6e, 0xc0, 0x9c, 0xaa,
	0x7e, 0x87, 0xd1, 0x70, 0x8b, 0x0b, 0x26, 0x79, 0x50, 0x99, 0x94, 0x20, 0xdf, 0xc6, 0xa5, 0x2a,
	0x6b, 0x28, 0x9d, 0x67, 0x2b, 0x10, 0x2f, 0xbd, 0xdb, 0xb0, 0xb6, 0x61, 0x7e, 0x44, 0x32, 0x02,
	0xbe, 0x07, 0xcf, 0xc7, 0xa1, 0x88, 0x78, 0x39, 0x15, 0x11, 0x63, 0x93, 0x90, 0xfd, 0x02, 0xd6,
	0x3a, 0x2c, 0x1c, 0x51, 0x12, 0xe5, 0xde, 0x07, 0x3b, 0x01, 0x0d, 0x63, 0xdc, 0x02, 0xe4, 0xb8,
	0x7c, 0x56, 0x6a, 0xd3, 0x15, 0xfd, 0x60, 0x85, 0x70, 0x29, 0x25, 0x13, 0x59, 0x6f, 0xc3, 0x74,
	0x2c, 0x25, 0xf7, 0xf3, 0x99, 0xd3, 0xc0, 0x1e, 0x56, 0xb0, 0x3e, 0x83, 0x0b, 0x4a, 0x73, 0xb3,
	0xd9, 0x1c, 0x90, 0x8d, 0x49, 0xdf, 0x06, 0x38, 0x3c, 0x6b, 0xb8, 0x39, 0x57, 0x1c, 0x3c, 0x3f,
	0xf2, 0xb0, 0x39, 0xfa, 0xc6, 0xe0, 0x91, 0x73, 0xb6, 0x3c, 0x9f, 0x62, 0x6e, 0x25, 0x91, 0x69,
	0x3d, 0x34, 0xe0, 0xe2, 0x31, 0x42, 0x67, 0x62, 0x8c, 0xbc, 0x33, 0x00, 0x3e, 0xa9, 0xc0, 0x17,
	0xc7, 0x82, 0x6b, 0x96, 0x01, 0xf2, 0x59, 0x38, 0xd7, 0xff, 0x2a, 0xfd, 0x93, 0xfe, 0x31, 0x9e,
	0x7f, 0x5c, 0x44, 0x0b, 0x9b, 0x90, 0x93, 0x98, 0x31, 0xfe, 0x42, 0x1a, 0xbe, 0xcc, 0x4c, 0xa2,
	0xeb, 0x4c, 0xeb, 0x22, 0x9c, 0x4f, 0x9c, 0x01, 0xde, 0x2c, 0x7b, 0x4d, 0x2f, 0xa8, 0xc7, 0x5b,
	0x6a, 0x7d, 0x65, 0xe0, 0xf7, 0x3a, 0xf2, 0x1e, 0x11, 0x3e, 0x87, 0xe7, 0x6a, 0x7a, 0x09, 0x21,
	0xe6, 0x07, 0x3c, 0xc7, 0x6e, 0xdf, 0xe2, 0x2c, 0x28, 0xaf, 0x49, 0xf5, 0x1f, 0xff, 0x2e, 0x2d,
	0xf9, 0x2c, 0xda, 0xee, 0xd4, 0x9c, 0x3a, 0x6f, 0x61, 0x67, 0xc0, 0x5f, 0xb6, 0x68, 0xdc, 0xc3,
	0x8e, 0x24, 0x13, 0x84, 0x26, 0x8d, 0x05, 0xac, 0x32, 0x94, 0x14, 0xcb, 0x2d, 0x11, 0xb1, 0x96,
	0x17, 0x51, 0xc9, 0x54, 0xd1, 0x0e, 0x33, 0xdf, 0xcb, 0xaf, 0x27, 0xf1, 0xba, 0x8c, 0x2c, 0x82,
	0xa6, 0x04, 0xcc, 0x48, 0xfa, 0x2a, 0x6e, 0xdf, 0x99, 0x39, 0xcb, 0xcb, 0x4a, 0x28, 0x4e, 0x3a,
	0xf0, 0x42, 0x8d, 0x07, 0x1d, 0xd1, 0x57, 0x9d, 0x3c, 0x23, 0xd5, 0x19, 0x25, 0x83, 0xb2, 0xd6,
	0xed, 0xc4, 0x01, 0xb8, 0xcb, 0x23, 0x16, 0xf8, 0x5b, 0x7c, 0xe7, 0xb0, 0x73, 0x38, 0x90, 0xeb,
	0xf2, 0x28, 0xee, 0x1c, 0xe5, 0xb9, 0x27, 0x0f, 0xec, 0x02, 0x02, 0x6d, 0x36, 0x1a, 0x21, 0x15,
	0xe2, 0xa3, 0x28, 0x64, 0x81, 0x5f, 0xd1, 0x61, 0x56, 0x94, 0x38, 0x2f, 0x03, 0xe5, 0x70, 0x6b,
	0xef, 0xc0, 0x4c, 0x57, 0x2d, 0x57, 0xdb, 0x72, 0x1d, 0xcb, 0xae, 0x48, 0x27, 0x7f, 0x3d, 0x2d,
	0x9d, 0xd7, 0xa5, 0x45, 0xe3, 0x9e, 0xc3, 0xb8, 0xdb, 0xf2, 0xa2, 0x6d, 0xe7, 0x7d, 0xea, 0x7b,
	0xf5, 0xde, 0x4d, 0x5a, 0x7f, 0xf2, 0xc0, 0x06, 0x54, 0xbe, 0x49, 0xeb, 0x95, 0x7c, 0xf7, 0xb0,
	0xfa, 0xea, 0xaf, 0x79, 0xc8, 0x29, 0x59, 0xf2, 0xbd, 0x01, 0x53, 0xba, 0xa5, 0x13, 0x27, 0xed,
	0x3a, 0x1c, 0x9d, 0x26, 0xa6, 0x9b, 0x39, 0x5e, 0x7b, 0xb1, 0x96, 0xbf, 0xfc, 0xfd, 0xdf, 0xef,
	0x26, 0x2f, 0x13, 0xcb, 0x1d, 0x3b, 0x89, 0xc9, 0x43, 0x03, 0x66, 0x92, 0x7d, 0x88, 0x5c, 0x1b,
	0xab, 0x36, 0x62, 0xee, 0x98, 0x6b, 0x27, 0xcc, 0x42, 0xd2, 0xeb, 0x8a, 0xf4, 0x1a, 0x59, 0x4d,
	0x25, 0xc5, 0x2c, 0x77, 0x37, 0x71, 0x85, 0xf6, 0xc8, 0x6f, 0x06, 0x14, 0x46, 0x4d, 0x08, 0xb2,
	0x71, 0x22, 0x96, 0xa1, 0x91, 0x64, 0xbe, 0x79, 0xca, 0x6c, 0x74, 0xb4, 0xa6, 0x1c, 0xb9, 0xc4,
	0xce, 0xe2, 0x48, 0xb8, 0xbb, 0x6a, 0xe2, 0xed, 0x91, 0x9f, 0x0d, 0x78, 0x69, 0x78, 0x22, 0x90,
	0xf5, 0xb1, 0x28, 0xc7, 0x4c, 0x2b, 0xf3, 0x8d, 0x53, 0x64, 0xa2, 0x01, 0x5b, 0x19, 0x58, 0x24,
	0xaf, 0x64, 0x32, 0x40, 0xbe, 0x35, 0x20, 0xa7, 0x9a, 0x3f, 0xb1, 0x33, 0x6d, 0x5c, 0x1f, 0xd1,
	0xc9, 0x1a, 0x8e, 0x5c, 0xaf, 0x2a, 0xae, 0x97, 0xc9, 0xa5, 0x34, 0x2e, 0x35, 0x3b, 0xe4, 0x66,
	0xbe, 0x38, 0x34, 0x17, 0xc8, 0xeb, 0x19, 0x3f, 0xeb, 0xf0, 0xa4, 0x31, 0xd7, 0x4f, 0x9e, 0x88,
	0xc4, 0x57, 0x15, 0xf1, 0x32, 0x59, 0x4a, 0xdf, 0x49, 0xde, 0xac, 0xe2, 0x20, 0x21, 0x7f, 0x18,
	0x30, 0x3b, 0xa2, 0xff, 0x93, 0x1b, 0x63, 0x19, 0x8e, 0x1f, 0x3d, 0xe6, 0xc6, 0xe9, 0x92, 0xd1,
	0x44, 0x59, 0x99, 0xd8, 0x20, 0xd7, 0xd3, 0x4c, 0x50, 0x2c, 0x10, 0x8f, 0x88, 0xa1, 0x9b, 0xfa,
	0x0b, 0x7e, 0x8f, 0x44, 0xdf, 0xcd, 0xf8, 0x3d, 0x8e, 0x36, 0xfe, 0x8c, 0xdf, 0x63, 0x44, 0x8b,
	0xb7, 0xd6, 0x95, 0x95, 0x55, 0x72, 0x35, 0xcd, 0x4a, 0x72, 0x08, 0xb8, 0xbb, 0x6a, 0x76, 0xec,
	0x95, 0xef, 0x3e, 0xda, 0x2f, 0x1a, 0x8f, 0xf7, 0x8b, 0xc6, 0x3f, 0xfb, 0x45, 0xe3, 0x9b, 0x83,
	0xe2, 0xc4, 0xe3, 0x83, 0xe2, 0xc4, 0x9f, 0x07, 0xc5, 0x89, 0x4f, 0x36, 0x92, 0x23, 0x2e, 0xec,
	0xb5, 0x23, 0x6e, 0xf3, 0xd0, 0xb7, 0x95, 0x80, 0x96, 0xb1, 0x95, 0xce, 0x17, 0x43, 0x4a, 0x6a,
	0xf8, 0xd5, 0xa6, 0xd4, 0x3f, 0x11, 0xaf, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xd0, 0x68,
	0xa3, 0x89, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the tieredrewards module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// TierPosition returns a single position by ID.
	TierPosition(ctx context.Context, in *QueryTierPositionRequest, opts ...grpc.CallOption) (*QueryTierPositionResponse, error)
	// TierPositionsByOwner returns all positions for a given owner address.
	TierPositionsByOwner(ctx context.Context, in *QueryTierPositionsByOwnerRequest, opts ...grpc.CallOption) (*QueryTierPositionsByOwnerResponse, error)
	// AllTierPositions returns all positions with pagination.
	AllTierPositions(ctx context.Context, in *QueryAllTierPositionsRequest, opts ...grpc.CallOption) (*QueryAllTierPositionsResponse, error)
	// Tiers returns all tier definitions.
	Tiers(ctx context.Context, in *QueryTiersRequest, opts ...grpc.CallOption) (*QueryTiersResponse, error)
	// TierPoolBalance returns the current balance of the bonus rewards pool.
	TierPoolBalance(ctx context.Context, in *QueryTierPoolBalanceRequest, opts ...grpc.CallOption) (*QueryTierPoolBalanceResponse, error)
	// EstimateTierRewards estimates pending base and bonus rewards for a position
	// without claiming them.
	EstimateTierRewards(ctx context.Context, in *QueryEstimateTierRewardsRequest, opts ...grpc.CallOption) (*QueryEstimateTierRewardsResponse, error)
	// TierVotingPower returns the governance voting power from delegated tier
	// positions for a given address.
	TierVotingPower(ctx context.Context, in *QueryTierVotingPowerRequest, opts ...grpc.CallOption) (*QueryTierVotingPowerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TierPosition(ctx context.Context, in *QueryTierPositionRequest, opts ...grpc.CallOption) (*QueryTierPositionResponse, error) {
	out := new(QueryTierPositionResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/TierPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TierPositionsByOwner(ctx context.Context, in *QueryTierPositionsByOwnerRequest, opts ...grpc.CallOption) (*QueryTierPositionsByOwnerResponse, error) {
	out := new(QueryTierPositionsByOwnerResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/TierPositionsByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllTierPositions(ctx context.Context, in *QueryAllTierPositionsRequest, opts ...grpc.CallOption) (*QueryAllTierPositionsResponse, error) {
	out := new(QueryAllTierPositionsResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/AllTierPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Tiers(ctx context.Context, in *QueryTiersRequest, opts ...grpc.CallOption) (*QueryTiersResponse, error) {
	out := new(QueryTiersResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/Tiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TierPoolBalance(ctx context.Context, in *QueryTierPoolBalanceRequest, opts ...grpc.CallOption) (*QueryTierPoolBalanceResponse, error) {
	out := new(QueryTierPoolBalanceResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/TierPoolBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EstimateTierRewards(ctx context.Context, in *QueryEstimateTierRewardsRequest, opts ...grpc.CallOption) (*QueryEstimateTierRewardsResponse, error) {
	out := new(QueryEstimateTierRewardsResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/EstimateTierRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TierVotingPower(ctx context.Context, in *QueryTierVotingPowerRequest, opts ...grpc.CallOption) (*QueryTierVotingPowerResponse, error) {
	out := new(QueryTierVotingPowerResponse)
	err := c.cc.Invoke(ctx, "/chainmain.tieredrewards.v1.Query/TierVotingPower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the tieredrewards module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// TierPosition returns a single position by ID.
	TierPosition(context.Context, *QueryTierPositionRequest) (*QueryTierPositionResponse, error)
	// TierPositionsByOwner returns all positions for a given owner address.
	TierPositionsByOwner(context.Context, *QueryTierPositionsByOwnerRequest) (*QueryTierPositionsByOwnerResponse, error)
	// AllTierPositions returns all positions with pagination.
	AllTierPositions(context.Context, *QueryAllTierPositionsRequest) (*QueryAllTierPositionsResponse, error)
	// Tiers returns all tier definitions.
	Tiers(context.Context, *QueryTiersRequest) (*QueryTiersResponse, error)
	// TierPoolBalance returns the current balance of the bonus rewards pool.
	TierPoolBalance(context.Context, *QueryTierPoolBalanceRequest) (*QueryTierPoolBalanceResponse, error)
	// EstimateTierRewards estimates pending base and bonus rewards for a position
	// without claiming them.
	EstimateTierRewards(context.Context, *QueryEstimateTierRewardsRequest) (*QueryEstimateTierRewardsResponse, error)
	// TierVotingPower returns the governance voting power from delegated tier
	// positions for a given address.
	TierVotingPower(context.Context, *QueryTierVotingPowerRequest) (*QueryTierVotingPowerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TierPosition(ctx context.Context, req *QueryTierPositionRequest) (*QueryTierPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TierPosition not implemented")
}
func (*UnimplementedQueryServer) TierPositionsByOwner(ctx context.Context, req *QueryTierPositionsByOwnerRequest) (*QueryTierPositionsByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TierPositionsByOwner not implemented")
}
func (*UnimplementedQueryServer) AllTierPositions(ctx context.Context, req *QueryAllTierPositionsRequest) (*QueryAllTierPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllTierPositions not implemented")
}
func (*UnimplementedQueryServer) Tiers(ctx context.Context, req *QueryTiersRequest) (*QueryTiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tiers not implemented")
}
func (*UnimplementedQueryServer) TierPoolBalance(ctx context.Context, req *QueryTierPoolBalanceRequest) (*QueryTierPoolBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TierPoolBalance not implemented")
}
func (*UnimplementedQueryServer) EstimateTierRewards(ctx context.Context, req *QueryEstimateTierRewardsRequest) (*QueryEstimateTierRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateTierRewards not implemented")
}
func (*UnimplementedQueryServer) TierVotingPower(ctx context.Context, req *QueryTierVotingPowerRequest) (*QueryTierVotingPowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TierVotingPower not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TierPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTierPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TierPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/TierPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TierPosition(ctx, req.(*QueryTierPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TierPositionsByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTierPositionsByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TierPositionsByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/TierPositionsByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TierPositionsByOwner(ctx, req.(*QueryTierPositionsByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllTierPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTierPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllTierPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/AllTierPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllTierPositions(ctx, req.(*QueryAllTierPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Tiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Tiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/Tiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Tiers(ctx, req.(*QueryTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TierPoolBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTierPoolBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TierPoolBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/TierPoolBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TierPoolBalance(ctx, req.(*QueryTierPoolBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EstimateTierRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEstimateTierRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EstimateTierRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/EstimateTierRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EstimateTierRewards(ctx, req.(*QueryEstimateTierRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TierVotingPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTierVotingPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TierVotingPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainmain.tieredrewards.v1.Query/TierVotingPower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TierVotingPower(ctx, req.(*QueryTierVotingPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chainmain.tieredrewards.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TierPosition",
			Handler:    _Query_TierPosition_Handler,
		},
		{
			MethodName: "TierPositionsByOwner",
			Handler:    _Query_TierPositionsByOwner_Handler,
		},
		{
			MethodName: "AllTierPositions",
			Handler:    _Query_AllTierPositions_Handler,
		},
		{
			MethodName: "Tiers",
			Handler:    _Query_Tiers_Handler,
		},
		{
			MethodName: "TierPoolBalance",
			Handler:    _Query_TierPoolBalance_Handler,
		},
		{
			MethodName: "EstimateTierRewards",
			Handler:    _Query_EstimateTierRewards_Handler,
		},
		{
			MethodName: "TierVotingPower",
			Handler:    _Query_TierVotingPower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainmain/tieredrewards/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTierPositionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierPositionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierPositionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PositionId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTierPositionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierPositionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierPositionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Position.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTierPositionsByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierPositionsByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierPositionsByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTierPositionsByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierPositionsByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierPositionsByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTierPositionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTierPositionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTierPositionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTierPositionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTierPositionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTierPositionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTiersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTiersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTiersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTiersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTiersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTiersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tiers) > 0 {
		for iNdEx := len(m.Tiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTierPoolBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierPoolBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierPoolBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTierPoolBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierPoolBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierPoolBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Balance) > 0 {
		for iNdEx := len(m.Balance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Balance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEstimateTierRewardsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEstimateTierRewardsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEstimateTierRewardsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PositionId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PositionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEstimateTierRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEstimateTierRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEstimateTierRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BonusRewards) > 0 {
		for iNdEx := len(m.BonusRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BonusRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.BaseRewards) > 0 {
		for iNdEx := len(m.BaseRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BaseRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTierVotingPowerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierVotingPowerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierVotingPowerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTierVotingPowerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTierVotingPowerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTierVotingPowerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.VotingPower.Size()
		i -= size
		if _, err := m.VotingPower.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTierPositionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PositionId != 0 {
		n += 1 + sovQuery(uint64(m.PositionId))
	}
	return n
}

func (m *QueryTierPositionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Position.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTierPositionsByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTierPositionsByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAllTierPositionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTierPositionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTiersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTiersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tiers) > 0 {
		for _, e := range m.Tiers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryTierPoolBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTierPoolBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Balance) > 0 {
		for _, e := range m.Balance {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryEstimateTierRewardsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PositionId != 0 {
		n += 1 + sovQuery(uint64(m.PositionId))
	}
	return n
}

func (m *QueryEstimateTierRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BaseRewards) > 0 {
		for _, e := range m.BaseRewards {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.BonusRewards) > 0 {
		for _, e := range m.BonusRewards {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryTierVotingPowerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTierVotingPowerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VotingPower.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierPositionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierPositionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierPositionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierPositionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierPositionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierPositionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Position.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierPositionsByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierPositionsByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierPositionsByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierPositionsByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierPositionsByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierPositionsByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, Position{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTierPositionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTierPositionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTierPositionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTierPositionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTierPositionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTierPositionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, Position{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTiersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTiersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTiersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTiersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTiersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTiersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tiers = append(m.Tiers, Tier{})
			if err := m.Tiers[len(m.Tiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierPoolBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierPoolBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierPoolBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierPoolBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierPoolBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierPoolBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balance = append(m.Balance, types.Coin{})
			if err := m.Balance[len(m.Balance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEstimateTierRewardsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEstimateTierRewardsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEstimateTierRewardsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionId", wireType)
			}
			m.PositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEstimateTierRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEstimateTierRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEstimateTierRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseRewards = append(m.BaseRewards, types.Coin{})
			if err := m.BaseRewards[len(m.BaseRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BonusRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BonusRewards = append(m.BonusRewards, types.Coin{})
			if err := m.BonusRewards[len(m.BonusRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierVotingPowerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierVotingPowerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierVotingPowerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTierVotingPowerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTierVotingPowerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTierVotingPowerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VotingPower.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
